2020-03-27 03:04:22,101 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-03-27 03:06:57,856 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-03-31 01:56:31,415 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-03-31 01:56:56,943 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-03-31 02:44:59,696 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-03-31 02:46:21,725 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-03-31 02:48:01,282 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-03-31 02:49:43,262 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 05:28:50,316 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 05:41:51,273 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 10:28:50,670 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 10:29:12,489 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 10:46:56,087 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 16:48:20,434 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 16:48:28,893 ERROR: Exception on / [GET] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 26, in index
    form=form, posts=posts)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/index.html", line 17, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-04-13 16:48:35,245 ERROR: Exception on /index [GET] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 26, in index
    form=form, posts=posts)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/index.html", line 17, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-04-13 16:49:35,346 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 16:51:00,484 ERROR: Exception on /explore [GET] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 55, in explore
    page, app.config['POSTS_PER_PAGE'], False)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 484, in paginate
    if page < 1:
TypeError: '<' not supported between instances of 'str' and 'int'
2020-04-13 16:51:06,236 ERROR: Exception on /explore [GET] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 55, in explore
    page, app.config['POSTS_PER_PAGE'], False)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 484, in paginate
    if page < 1:
TypeError: '<' not supported between instances of 'str' and 'int'
2020-04-13 16:51:51,746 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 17:06:36,253 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
