2020-04-23 14:04:23,316 ERROR: Exception on /reset_password_request [POST] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 13, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-04-23 14:05:27,557 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 14:05:57,184 ERROR: Exception on /reset_password_request [POST] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 13, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-04-23 14:09:24,101 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 14:09:44,188 ERROR: Exception on /reset_password_request [POST] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 19, in send_password_reset_email
    user=user, token=token))
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 6, in send_email
    msg = Message(subject, sender=sender, recipient=recipients)
NameError: name 'subject' is not defined
2020-04-23 14:10:34,663 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 14:10:50,048 ERROR: Exception on /reset_password_request [POST] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 19, in send_password_reset_email
    user=user, token=token))
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 6, in send_email
    msg = Message(subject, sender=sender, recipient=recipients)
TypeError: __init__() got an unexpected keyword argument 'recipient'
2020-04-23 14:12:11,219 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 14:12:17,281 ERROR: Exception on /reset_password_request [POST] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 19, in send_password_reset_email
    user=user, token=token))
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 8, in send_email
    msg.html = html_mody
NameError: name 'html_mody' is not defined
2020-04-23 14:12:42,767 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 18:11:04,252 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:55]
2020-04-23 20:09:05,429 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:55]
2020-04-23 23:06:22,251 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-23 23:18:45,950 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:27:46,990 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:28:45,120 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:31:00,610 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:39:26,536 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:39:54,753 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:41:22,460 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:42:35,726 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:45:38,003 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:51:13,769 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:52:10,045 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 03:52:40,056 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 04:01:01,949 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 04:15:01,302 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 04:15:27,430 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 05:42:57,621 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
2020-04-24 08:02:02,654 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:57]
